/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 26
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_COMMA = 1,
  anon_sym_COLON = 2,
  anon_sym_DOT = 3,
  anon_sym_POUND = 4,
  sym_register = 5,
  aux_sym_immediate_token1 = 6,
  aux_sym_immediate_token2 = 7,
  aux_sym_immediate_token3 = 8,
  sym_string = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  sym_identifier = 12,
  sym_comment = 13,
  sym_source_file = 14,
  sym__statement = 15,
  sym_instruction = 16,
  sym_label = 17,
  sym_assembler_directive = 18,
  sym_preprocessor_directive = 19,
  sym_operand = 20,
  sym_immediate = 21,
  sym_memory_reference = 22,
  aux_sym_source_file_repeat1 = 23,
  aux_sym_instruction_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_COMMA] = ",",
  [anon_sym_COLON] = ":",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [sym_register] = "register",
  [aux_sym_immediate_token1] = "immediate_token1",
  [aux_sym_immediate_token2] = "immediate_token2",
  [aux_sym_immediate_token3] = "immediate_token3",
  [sym_string] = "string",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_instruction] = "instruction",
  [sym_label] = "label",
  [sym_assembler_directive] = "assembler_directive",
  [sym_preprocessor_directive] = "preprocessor_directive",
  [sym_operand] = "operand",
  [sym_immediate] = "immediate",
  [sym_memory_reference] = "memory_reference",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_instruction_repeat1] = "instruction_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_register] = sym_register,
  [aux_sym_immediate_token1] = aux_sym_immediate_token1,
  [aux_sym_immediate_token2] = aux_sym_immediate_token2,
  [aux_sym_immediate_token3] = aux_sym_immediate_token3,
  [sym_string] = sym_string,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_instruction] = sym_instruction,
  [sym_label] = sym_label,
  [sym_assembler_directive] = sym_assembler_directive,
  [sym_preprocessor_directive] = sym_preprocessor_directive,
  [sym_operand] = sym_operand,
  [sym_immediate] = sym_immediate,
  [sym_memory_reference] = sym_memory_reference,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_instruction_repeat1] = aux_sym_instruction_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_register] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_immediate_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_immediate_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_immediate_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_instruction] = {
    .visible = true,
    .named = true,
  },
  [sym_label] = {
    .visible = true,
    .named = true,
  },
  [sym_assembler_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_preprocessor_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_operand] = {
    .visible = true,
    .named = true,
  },
  [sym_immediate] = {
    .visible = true,
    .named = true,
  },
  [sym_memory_reference] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_instruction_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_opcode = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_opcode] = "opcode",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_opcode, 0},
  [1] =
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(6);
      ADVANCE_MAP(
        '"', 1,
        '#', 10,
        ',', 7,
        '.', 9,
        '0', 15,
        ':', 8,
        ';', 26,
        '[', 18,
        ']', 19,
        'b', 22,
        'd', 20,
        'f', 21,
        'i', 23,
        'q', 24,
        's', 23,
        'w', 24,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(16);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(17);
      if (lookahead == '\\') ADVANCE(4);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(14);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 4:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '#') ADVANCE(10);
      if (lookahead == ',') ADVANCE(7);
      if (lookahead == '.') ADVANCE(9);
      if (lookahead == ';') ADVANCE(26);
      if (lookahead == ']') ADVANCE(19);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_register);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_immediate_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_immediate_token2);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(14);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(aux_sym_immediate_token3);
      if (lookahead == 'b') ADVANCE(2);
      if (lookahead == 'x') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_immediate_token3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(24);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(12);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(26);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 5},
  [6] = {.lex_state = 5},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 5},
  [11] = {.lex_state = 5},
  [12] = {.lex_state = 5},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 5},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 5},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_register] = ACTIONS(1),
    [aux_sym_immediate_token1] = ACTIONS(1),
    [aux_sym_immediate_token2] = ACTIONS(1),
    [aux_sym_immediate_token3] = ACTIONS(1),
    [sym_string] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(24),
    [sym__statement] = STATE(5),
    [sym_instruction] = STATE(5),
    [sym_label] = STATE(5),
    [sym_assembler_directive] = STATE(5),
    [sym_preprocessor_directive] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_DOT] = ACTIONS(5),
    [anon_sym_POUND] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_operand] = STATE(14),
    [sym_immediate] = STATE(11),
    [sym_memory_reference] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(13),
    [anon_sym_COLON] = ACTIONS(15),
    [anon_sym_DOT] = ACTIONS(13),
    [anon_sym_POUND] = ACTIONS(13),
    [sym_register] = ACTIONS(17),
    [aux_sym_immediate_token1] = ACTIONS(19),
    [aux_sym_immediate_token2] = ACTIONS(19),
    [aux_sym_immediate_token3] = ACTIONS(21),
    [sym_string] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_identifier] = ACTIONS(27),
    [sym_comment] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_operand] = STATE(19),
    [sym_immediate] = STATE(11),
    [sym_memory_reference] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(30),
    [anon_sym_DOT] = ACTIONS(30),
    [anon_sym_POUND] = ACTIONS(30),
    [sym_register] = ACTIONS(17),
    [aux_sym_immediate_token1] = ACTIONS(19),
    [aux_sym_immediate_token2] = ACTIONS(19),
    [aux_sym_immediate_token3] = ACTIONS(21),
    [sym_string] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_identifier] = ACTIONS(32),
    [sym_comment] = ACTIONS(30),
  },
  [STATE(4)] = {
    [sym_operand] = STATE(20),
    [sym_immediate] = STATE(11),
    [sym_memory_reference] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(35),
    [anon_sym_DOT] = ACTIONS(35),
    [anon_sym_POUND] = ACTIONS(35),
    [sym_register] = ACTIONS(17),
    [aux_sym_immediate_token1] = ACTIONS(19),
    [aux_sym_immediate_token2] = ACTIONS(19),
    [aux_sym_immediate_token3] = ACTIONS(21),
    [sym_string] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(25),
    [sym_identifier] = ACTIONS(37),
    [sym_comment] = ACTIONS(35),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(5), 1,
      anon_sym_DOT,
    ACTIONS(7), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(40), 1,
      ts_builtin_sym_end,
    ACTIONS(42), 1,
      sym_comment,
    STATE(6), 6,
      sym__statement,
      sym_instruction,
      sym_label,
      sym_assembler_directive,
      sym_preprocessor_directive,
      aux_sym_source_file_repeat1,
  [24] = 6,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    ACTIONS(46), 1,
      anon_sym_DOT,
    ACTIONS(49), 1,
      anon_sym_POUND,
    ACTIONS(52), 1,
      sym_identifier,
    ACTIONS(55), 1,
      sym_comment,
    STATE(6), 6,
      sym__statement,
      sym_instruction,
      sym_label,
      sym_assembler_directive,
      sym_preprocessor_directive,
      aux_sym_source_file_repeat1,
  [48] = 7,
    ACTIONS(21), 1,
      aux_sym_immediate_token3,
    ACTIONS(23), 1,
      sym_string,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(21), 1,
      sym_operand,
    ACTIONS(17), 2,
      sym_register,
      sym_identifier,
    ACTIONS(19), 2,
      aux_sym_immediate_token1,
      aux_sym_immediate_token2,
    STATE(11), 2,
      sym_immediate,
      sym_memory_reference,
  [73] = 7,
    ACTIONS(21), 1,
      aux_sym_immediate_token3,
    ACTIONS(23), 1,
      sym_string,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(17), 1,
      sym_operand,
    ACTIONS(17), 2,
      sym_register,
      sym_identifier,
    ACTIONS(19), 2,
      aux_sym_immediate_token1,
      aux_sym_immediate_token2,
    STATE(11), 2,
      sym_immediate,
      sym_memory_reference,
  [98] = 7,
    ACTIONS(21), 1,
      aux_sym_immediate_token3,
    ACTIONS(23), 1,
      sym_string,
    ACTIONS(25), 1,
      anon_sym_LBRACK,
    STATE(25), 1,
      sym_operand,
    ACTIONS(17), 2,
      sym_register,
      sym_identifier,
    ACTIONS(19), 2,
      aux_sym_immediate_token1,
      aux_sym_immediate_token2,
    STATE(11), 2,
      sym_immediate,
      sym_memory_reference,
  [123] = 1,
    ACTIONS(58), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_RBRACK,
      sym_identifier,
      sym_comment,
  [133] = 1,
    ACTIONS(60), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_RBRACK,
      sym_identifier,
      sym_comment,
  [143] = 3,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(62), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      sym_comment,
  [157] = 1,
    ACTIONS(66), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_RBRACK,
      sym_identifier,
      sym_comment,
  [167] = 3,
    ACTIONS(64), 1,
      anon_sym_COMMA,
    STATE(12), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(68), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      sym_comment,
  [181] = 3,
    ACTIONS(72), 1,
      anon_sym_COMMA,
    STATE(15), 1,
      aux_sym_instruction_repeat1,
    ACTIONS(70), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      sym_comment,
  [195] = 1,
    ACTIONS(75), 7,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_RBRACK,
      sym_identifier,
      sym_comment,
  [205] = 1,
    ACTIONS(70), 6,
      ts_builtin_sym_end,
      anon_sym_COMMA,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      sym_comment,
  [214] = 1,
    ACTIONS(77), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      sym_comment,
  [222] = 1,
    ACTIONS(79), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      sym_comment,
  [230] = 1,
    ACTIONS(81), 5,
      ts_builtin_sym_end,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      sym_comment,
  [238] = 2,
    ACTIONS(83), 1,
      anon_sym_COMMA,
    ACTIONS(85), 1,
      anon_sym_RBRACK,
  [245] = 1,
    ACTIONS(87), 1,
      sym_identifier,
  [249] = 1,
    ACTIONS(89), 1,
      sym_identifier,
  [253] = 1,
    ACTIONS(91), 1,
      ts_builtin_sym_end,
  [257] = 1,
    ACTIONS(93), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 24,
  [SMALL_STATE(7)] = 48,
  [SMALL_STATE(8)] = 73,
  [SMALL_STATE(9)] = 98,
  [SMALL_STATE(10)] = 123,
  [SMALL_STATE(11)] = 133,
  [SMALL_STATE(12)] = 143,
  [SMALL_STATE(13)] = 157,
  [SMALL_STATE(14)] = 167,
  [SMALL_STATE(15)] = 181,
  [SMALL_STATE(16)] = 195,
  [SMALL_STATE(17)] = 205,
  [SMALL_STATE(18)] = 214,
  [SMALL_STATE(19)] = 222,
  [SMALL_STATE(20)] = 230,
  [SMALL_STATE(21)] = 238,
  [SMALL_STATE(22)] = 245,
  [SMALL_STATE(23)] = 249,
  [SMALL_STATE(24)] = 253,
  [SMALL_STATE(25)] = 257,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 1, 0, 1),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_instruction, 1, 0, 1), SHIFT(11),
  [30] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preprocessor_directive, 2, 0, 2),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_preprocessor_directive, 2, 0, 2), SHIFT(11),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assembler_directive, 2, 0, 2),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_assembler_directive, 2, 0, 2), SHIFT(11),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_immediate, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operand, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 3, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memory_reference, 3, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_instruction, 2, 0, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_instruction_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_memory_reference, 5, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_label, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preprocessor_directive, 3, 0, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assembler_directive, 3, 0, 2),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [91] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_nyx(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "nyx",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
